for(i in 1:20){
  an<-sort(rnorm(i,1,1))
  bn<-sort(rnorm(i,1,1))
  cn<-sort(rnorm(i,1,1))
  dn<-sort(rnorm(i,1,1))
  en<-sort(rnorm(i,1,1))
  ac<-sort(rcauchy(i,1,1))
  bc<-sort(rcauchy(i,1,1))
  cc<-sort(rcauchy(i,1,1))
  dc<-sort(rcauchy(i,1,1))
  ec<-sort(rcauchy(i,1,1))
}
for(i in 1:100){
  fn<-sort(rnorm(i,1,1))
  gn<-sort(rnorm(i,1,1))
  hn<-sort(rnorm(i,1,1))
  inn<-sort(rnorm(i,1,1))
  jn<-sort(rnorm(i,1,1))
  kn<-sort(rnorm(i,1,1))
  ln<-sort(rnorm(i,1,1))
  mn<-sort(rnorm(i,1,1))
  nn<-sort(rnorm(i,1,1))
  fc<-sort(rcauchy(i,1,1))
  gc<-sort(rcauchy(i,1,1))
  hc<-sort(rcauchy(i,1,1))
  icc<-sort(rcauchy(i,1,1))
  jc<-sort(rcauchy(i,1,1))
  kc<-sort(rcauchy(i,1,1))
  lc<-sort(rcauchy(i,1,1))
  mc<-sort(rcauchy(i,1,1))
  nc<-sort(rcauchy(i,1,1))
}
for(i in 1:1000){
  on<-sort(rnorm(i,1,1))
  pn<-sort(rnorm(i,1,1))
  qn<-sort(rnorm(i,1,1))
  rn<-sort(rnorm(i,1,1))
  sn<-sort(rnorm(i,1,1))
  tn<-sort(rnorm(i,1,1))
  un<-sort(rnorm(i,1,1))
  vn<-sort(rnorm(i,1,1))
  wn<-sort(rnorm(i,1,1))
  oc<-sort(rcauchy(i,1,1))
  pc<-sort(rcauchy(i,1,1))
  qc<-sort(rcauchy(i,1,1))
  rc<-sort(rcauchy(i,1,1))
  sc<-sort(rcauchy(i,1,1))
  tc<-sort(rcauchy(i,1,1))
  uc<-sort(rcauchy(i,1,1))
  vc<-sort(rcauchy(i,1,1))
  wc<-sort(rcauchy(i,1,1))
}
step<-c(20,40,60,80,100,200,300,400,500,600,700,800,900,1000,2000,3000,4000,5000,6000,7000,8000,9000,10000)
medn<-c(median(an),median(bn),median(cn),median(dn),median(en),median(fn),median(gn),median(hn),median(inn),median(jn),median(kn),median(ln),median(mn),median(nn),median(on),median(pn),median(qn),median(rn),median(sn),median(tn),median(un),median(vn),median(wn))
medc<-c(median(ac),median(bc),median(cc),median(dc),median(ec),median(fc),median(gc),median(hc),median(icc),median(jc),median(kc),median(lc),median(mc),median(nc),median(oc),median(pc),median(qc),median(rc),median(sc),median(tc),median(uc),median(vc),median(wc))
avgn<-c(mean(an),mean(bn),mean(cn),mean(dn),mean(en),mean(fn),mean(gn),mean(hn),mean(inn),mean(jn),mean(kn),mean(ln),mean(mn),mean(nn),mean(on),mean(pn),mean(qn),mean(rn),mean(sn),mean(tn),mean(un),mean(vn),mean(wn))
avgc<-c(mean(ac),mean(bc),mean(cc),mean(dc),mean(ec),mean(fc),mean(gc),mean(hc),mean(icc),mean(jc),mean(kc),mean(lc),mean(mc),mean(nc),mean(oc),mean(pc),mean(qc),mean(rc),mean(sc),mean(tc),mean(uc),mean(vc),mean(wc))
plot(log(step),medn,main = "Median of N(1,1)")
plot(log(step),medc,main = "Median of C(1,1)")
plot(log(step),avgn,main = "AVGX of N(1,1)",ylim = c(0.8,1.5))
plot(log(step),avgc,main = "AVGX of C(1,1)",ylim = c(0.8,1.5))
